### ISSUE TITLE
Category not dispaying properly nor is it updating on save

### ISSUE THREAD

**Issue by claytoncollie** [cubeweb/acf-addons#11]
I have 3 different fields inside 1 field group in ACF.  Form, Firing, Technique.  They are associated with the subcategories for that post.  I am only including certain subcategories for a particular field to make it easier to see the subcategories of form, firing, and technique and to not use a multi-select drop down.  Novice WP users might have to use this section to update posts.

My post summary view is showing the post being associated with 3 subcategories while my post detail view is showing 3 different sub categories.  When I update the post, the changes are not reflected in the post summary view.  Just checked the database too and when selecting a new subcategory in the drop down field in the single post view, it does not update the post meta in the db nor does it add a post count next to the category in the backend of WP.

I'm guess it has something to do with me splitting up the sub categories into 3 different field groups instead of using a multi-select dropdown.  Is there a way to keep the 3 separate field objects inside my field group to make selecting subcategories easy for novice WP users?

![field-group](https://cloud.githubusercontent.com/assets/4236538/6311052/e1ed8502-b922-11e4-978a-b4c5426fea05.png)
![post single view](https://cloud.githubusercontent.com/assets/4236538/6311054/e4218508-b922-11e4-9037-d65fea3c87a9.png)
![post summary view](https://cloud.githubusercontent.com/assets/4236538/6311058/e7904ad0-b922-11e4-91c0-8106793f228a.png)

**Comment by cubeweb** [comment]
If I understand correctly, you want when you update the ACF Category field to update the post category too?

**Comment by claytoncollie** [comment]
yes.  I actually thought that was supposed to happen.  I didn't understand that it is a completely separate field that just accesses the names of the categories.

**Comment by cubeweb** [comment]
I released a version here in github that has that feature. But is still in beta. If you want to try it please do so and sent me any feedback.
